// <auto-generated />
using ECommBlazor1.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommBlazor1.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230407074706_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ECommBlazor1.Shared.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Books",
                            Url = "books"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Drinks",
                            Url = "drinks"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Video-Games",
                            Url = "games"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Clothing",
                            Url = "clothing"
                        });
                });

            modelBuilder.Entity("ECommBlazor1.Shared.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "The first two books of 'the book of the new sun' by renowned sci-fi author Gene Wolfe",
                            ImageUrl = "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1600272802l/55077689.jpg",
                            Price = 9.99m,
                            Title = "Shadow & Claw"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "C.S. Lewis's signature collection featuring a wide array of his fictional and Christian apolegetic works",
                            ImageUrl = "https://images.thenile.io/r1000/9780007500192.jpg",
                            Price = 19.99m,
                            Title = "C.S. Lewis - The Signature Collection"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "A tasty beverage championed by athletes and programmers alike",
                            ImageUrl = "https://www.restockit.com/images/product/xlarge/RDBRBD99124.jpg",
                            Price = 1.99m,
                            Title = "Red Bull"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Description = "Classic game for the Nintendo Gamecube",
                            ImageUrl = "https://cdn.mobygames.com/covers/6555565-metroid-prime-gamecube-front-cover.jpg",
                            Price = 59.99m,
                            Title = "Metroid Prime"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "Building/Survival game available for many platforms",
                            ImageUrl = "https://cdn.mobygames.com/covers/3364463-minecraft-nintendo-switch-front-cover.jpg",
                            Price = 9.99m,
                            Title = "Minecraft"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 4,
                            Description = "This hat is guaranteed to boost your confidence",
                            ImageUrl = "https://stores.wholesalecentral.com/Images/NMJ6J950PK_892KUVGLGLO_CQQQWUF/5297112446201.jpg",
                            Price = 19.99m,
                            Title = "Cool Hat"
                        });
                });

            modelBuilder.Entity("ECommBlazor1.Shared.Models.Product", b =>
                {
                    b.HasOne("ECommBlazor1.Shared.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
